baseURL = "http://ifaews01.pic.es/grh"
languageCode = "en-us"
title = "My New Hugo Site"

defaultContentLanguage = "es"
defaultContentLanguageInSubdir= true

#Syntax Highlighting
PygmentsCodeFences = true
PygmentsStyle = "manni"
PygmentsCodefencesGuessSyntax = true
#https://help.farbox.com/pygments.html

#Notebooks Server
[params]
  [params.Notebooks]
    1server = "https://mybinder.org/v2/gh/"
    2git = "IFAE/grh_website/master"
    3path ="?filepath=/notebooks/"


[languages]
[languages.en]
title = "Gamma Ray Hunters"
weight = 1

[languages.en.params]

[[languages.en.menu.main]]
identifier = "home"
name = "home"
url = "/"
weight = 1


[languages.es]
copyright = ""
title = "Cazadores de Rayos Gamma"
weight = 2
[languages.es.params]
linkedin = "lien-francais"
[languages.es.params.navigation]
help  = "Aide"
[[languages.es.menu.main]]
identifier = "inicio"
name = "inicio"
url = "/"
weight = 1

[languages.ca]
