baseURL = "https://www.cazadoresderayosgamma.com"
languageCode = "en-us"
title = "Cazadores de Rayos Gamma"

defaultContentLanguage = "es"
defaultContentLanguageInSubdir= true

#Syntax Highlighting
PygmentsCodeFences = true
PygmentsStyle = "manni"
PygmentsCodefencesGuessSyntax = true
#https://help.farbox.com/pygments.html

#DisqusShortname
disqusShortname = "CAZADORES"

#Notebooks Server
[params]
  [params.Notebooks.colab]
    urlPre = "https://colab.research.google.com/drive/"

[languages]
[languages.en]
title = "Gamma Ray Hunters"
weight = 1
[[languages.en.menu.main]]
identifier = "home"
name = "home"
url = "/en"
weight = 1
[languages.es]
title = "Cazadores de Rayos Gamma"
weight = 2
[[languages.es.menu.main]]
identifier = "inicio"
name = "inicio"
url = "/es"
weight = 1
[languages.ca]
title = "Caçadors de Raigs Gamma"
weight = 3
[[languages.ca.menu.main]]
identifier = "inici"
name = "inici"
url = "/ca"
weight = 1
